name: GTUBT
description: GTU BT mobile app.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter_bloc: 3.2.0
  equatable: ^1.1.0
  built_value: 6.7.1
  onesignal_flutter: ^2.0.0
  json_annotation:
  http: ^0.12.1
  flutter:
    sdk: flutter
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  basic_utils: ^2.5.3

  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: 1.6.8
  built_value_generator: 6.7.1
  json_serializable:

  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
